# Cloudflare Pages Configuration
name = "brainsait-mcp-landing"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "dist"

[env.production]
# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"

[env.staging] 
# Staging environment variables
[env.staging.vars]
ENVIRONMENT = "staging"