# Cloudflare Pages Configuration for BrainSAIT.io
name = "brainsait-mcp-landing"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "dist"

[env.production]
# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
DOMAIN = "brainsait.io"

[env.preview] 
# Preview environment variables  
[env.preview.vars]
ENVIRONMENT = "preview"
DOMAIN = "brainsait.io"

# Custom domains will be configured via Cloudflare dashboard:
# - mcp.brainsait.io (primary)
# - hospital.brainsait.io 
# - api.brainsait.io
# - docs.brainsait.io
# - support.brainsait.io